version: '3.8'

services:
  app:
    build:
      context: .   # Assuming Dockerfile is in the root of your project
      dockerfile: Dockerfile
    container_name: exchange
    ports:
      - "8080:8080"
    environment:
        SPRING_REDIS_HOST: redis
        SPRING_REDIS_PORT: 6379
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
